-- Alert system tables.
-- Run this once in Supabase SQL Editor.
create table if not exists public.user_alerts (
  id bigint generated by default as identity primary key,
  user_email text not null,
  ticker text not null,
  split_date date,
  enabled boolean not null default true,
  drop_enabled boolean not null default false,
  drop_mode text not null default 'percent' check (drop_mode in ('percent','price')),
  drop_value numeric,
  short_enabled boolean not null default false,
  short_value numeric,
  rsi_enabled boolean not null default false,
  rsi_value numeric,
  rsi_direction text not null default 'below' check (rsi_direction in ('above','below')),
  updated_at timestamptz not null default now(),
  unique(user_email,ticker)
);

create index if not exists user_alerts_email_idx on public.user_alerts(user_email);
create index if not exists user_alerts_ticker_idx on public.user_alerts(ticker);

create table if not exists public.stock_alerts (
  id bigint generated by default as identity primary key,
  user_email text not null,
  ticker text not null,
  alert_type text not null,
  title text,
  message text,
  created_at timestamptz not null default now(),
  payload jsonb
);

create index if not exists stock_alerts_email_created_idx on public.stock_alerts(user_email,created_at desc);

revoke all on table public.user_alerts from anon;
revoke all on table public.user_alerts from authenticated;
revoke all on table public.stock_alerts from anon;
revoke all on table public.stock_alerts from authenticated;
grant all on table public.user_alerts to service_role;
grant all on table public.stock_alerts to service_role;


-- Harden the alert tables for the server-side custom-auth architecture.
-- The site does NOT use Supabase Auth; Netlify/GitHub access these tables with
-- the service-role key. These policies keep anon/authenticated clients out.
alter table public.user_alerts enable row level security;
alter table public.stock_alerts enable row level security;
drop policy if exists user_alerts_service_role on public.user_alerts;
drop policy if exists stock_alerts_service_role on public.stock_alerts;
create policy user_alerts_service_role on public.user_alerts for all to service_role using (true) with check (true);
create policy stock_alerts_service_role on public.stock_alerts for all to service_role using (true) with check (true);
